//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dosya
    {
        public int id { get; set; }
        public string DosyaYolu { get; set; }
        public string Tarih { get; set; }
        public string mesaj { get; set; }
    }
}
